### ISSUE TITLE
GetToken

### ISSUE THREAD

**Issue by Listlessness** [NuroC/MooMooBot#24]
/app/src/functions/generate.js:2
module.exports = getToken;
                 ^
ReferenceError: getToken is not defined

**Comment by Listlessness** [comment]
Error: Cannot find module '../src/bot/commands/ping.js'

**Comment by Listlessness** [comment]
Nvm Fixed it But can you add me? ђєɭקɭєรร#3600

**Comment by NuroC** [comment]
sure.
